### ISSUE TITLE
Annotation Processing

### ISSUE THREAD

**Issue by zozero94** [zozero94/FeatureTestRepo#6]
어노테이션 프로세싱을 이용하여 컴파일 타임에 클래스를 만들어 보자.

**Comment by zojae031** [comment]
1. AutoService 디펜던시를 추가해서 하니 안됨
2. 직접 processor 모듈에 META-INF를 추가하니까 됨
<img width="572" alt="스크린샷 2020-11-03 오후 3 22 20" src="https://user-images.githubusercontent.com/31091115/97954984-5fb13800-1de8-11eb-82c3-107d5f43f43f.png">

<img width="437" alt="스크린샷 2020-11-03 오후 3 20 05" src="https://user-images.githubusercontent.com/31091115/97954876-0f39da80-1de8-11eb-9600-d8560961d1cd.png">

**Comment by zojae031** [comment]
**javax.annotation.processing.Processor** 내용
```com.example.annotation_processor.TestProcessor```

**Comment by zozero94** [comment]
https://www.charlezz.com/?p=1167
